name: Decode and Upload Security Keys

on:
  workflow_dispatch: 

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    # Required permission to delete artifacts using the GITHUB_TOKEN
    permissions:
      actions: write 
      
    steps:
      - name: Create security directory
        run: mkdir -p security

      - name: Decode secrets to files
        run: |
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/artisanrom_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/artisanrom_platform.x509.pem
          echo -n "${{ secrets.OTA_KEY_PK8 }}" | base64 --decode > security/artisanrom_ota.pk8
          echo -n "${{ secrets.OTA_KEY_PEM }}" | base64 --decode > security/artisanrom_ota.x509.pem

      - name: Upload security folder as artifact
        id: upload-step # We need this ID to get the artifact ID for deletion
        uses: actions/upload-artifact@v4
        with:
          name: artisanrom-keys
          path: security/
          retention-days: 1 # Standard minimum

      - name: Countdown for 2 minutes
        run: |
          echo "Artifact uploaded. You have 2 minutes to download it..."
          sleep 120

      - name: Delete Artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting artifact..."
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/artifacts/${{ steps.upload-step.outputs.artifact-id }}
